PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT ?place ?placeLabel ?location ?class ?classLabel WHERE {
  SERVICE wikibase:around {
    ?place wdt:P625 ?location.
    bd:serviceParam wikibase:center "Point(-89.466666666 43.55)"^^geo:wktLiteral.
    bd:serviceParam wikibase:radius "100".
    bd:serviceParam wikibase:distance ?dist.
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  { ?place (wdt:P31/wdt:P279) wd:Q15284. }
  UNION
  { ?place wdt:P31 wd:Q515. }
  UNION
  { ?place (wdt:P31/wdt:P279) wd:Q515. }
  UNION
  { ?place (wdt:P31/wdt:P279/wdt:P279) wd:Q515. }
  UNION
  { ?place (wdt:P31/wdt:P279/wdt:P279/wdt:P279) wd:Q515. }
  UNION
  { ?place (wdt:P31/wdt:P279) wd:Q3957. }
  UNION
  { ?place (wdt:P31/wdt:P279) wd:Q532. }
  UNION
  { ?place (wdt:P31/wdt:P279) wd:Q398141. }
  OPTIONAL {?place wdt:P31  ?class.}
}
ORDER BY ?placeLabel